### PR TITLE
Changes paths to match Windows standards.

### LINKED ISSUE #16: UserData on Windows should be local.
On Windows, `AppData` may be synced over the network on login/logout.  Because of this, it is not recommended to store large user data in it and instead only store small config data.  Since there is a separate entry for `UserConfig`, I believe the correct place for `UserData` is in `LocalAppData` (where you currently put `UserCache`).

### PR DESCRIPTION
**Pull request by MicahZoltu**
Fixes #16 and #17.

This changes the location of several folders to match Windows standards.  The full list can be found at https://msdn.microsoft.com/en-us/library/windows/desktop/dd378457(v=vs.85).aspx, though you will have to go to other MSDN articles to get details of their intended use:
[Local App Data](https://msdn.microsoft.com/en-us/windows/uwp/app-settings/store-and-retrieve-app-data#local-app-data)
[Roaming App Data](https://msdn.microsoft.com/en-us/windows/uwp/app-settings/store-and-retrieve-app-data#roaming-data)
[Program Data](https://msdn.microsoft.com/en-us/library/mt674655%28v=vs.85%29.aspx#10._apps_must_install_to_the_correct_folders_by_default)

Note: This is a breaking change so if this project follows semantic versioning it should be released as a major version bump.

### CODE REVIEW

**Comment by MicahZoltu** [comment]
Oops, I should have checked existing PRs first, this *partially* mirrors #15.  I'll leave my feedback on that issue there and if it is merged I would be happy to rebase this PR.

**Comment by AndyBarron** [comment]
Merged #15, rebase if you please 😄

**Comment by MicahZoltu** [comment]
Rebased.  Thanks for maintaining this project!

**Comment by AndyBarron** [comment]
My pleasure 👌 Merging now!

**Pull request merged**
