### PR TITLE
Implement Redox support

### PR DESCRIPTION
**Pull request by jackpot51**
This implements Redox support, using the standard locations for app information.

### CODE REVIEW

**Comment by jackpot51** [comment]
@AndyBarron can you take a look at this?

**Comment by mmstick** [comment]
Needed in a point release by the Ion shell in order to publish a new Ion point release on Crates.io.

**Comment by mqudsi** [comment]
@AndyBarron bump?

**Comment by mmstick** [comment]
@icefoxen That's good news! We had to move to using `xdg` instead.

**Pull request merged**
