### PR TITLE
Fix compilation on nightly Rust

### PR DESCRIPTION
**Pull request by koute**
Fixes https://github.com/AndyBarron/app-dirs-rs/issues/28

### CODE REVIEW

**Comment by AndyBarron** [comment]
Thanks so much for this!! I've been super busy lately unfortunately, but should have time to merge & deploy this and some other fixes.

**Comment by SebAubin** [comment]
Can someone merge this fix for the nightly please?

**Comment by kornelski** [comment]
@AndyBarron could you make a quick release with this now? It is causing breakage in dependent projects.

**Comment by loovjo** [comment]
For everyone needing this: you can add the following to your `Cargo.toml` to use this patch right now:

    [patch.crates-io]
    app_dirs = { git = "https://github.com/koute/app-dirs-rs" }

**Comment by PSeitz** [comment]
So if this speeds up things, I tested it and it works.

**Comment by faern** [comment]
This problem exists on the latest beta, `rustc 1.25.0-beta.6`. So I guess the compiler change triggering this will exist in 1.25.0 stable as well. That means this must be merged and published before March 29 unless we want this bug to regress into stable, which would be very sad.

Would probably have to be published quite a while before that so people have some time to update their `Cargo.lock` files before Travis CI and similar systems automatically upgrade to rustc 1.25.0.

**Comment by koute** [comment]
@AndyBarron If you don't have the time to maintain this crate anymore then perhaps you could share co-maintainership with someone else? (I'm sure *someone* would be interested in helping out.)

**Comment by luser** [comment]
I use app_dirs in sccache and I'd be happy to help out with some light maintenance if you'd like.

**Comment by icefoxen** [comment]
I've forked this crate with the intent of making sure it stays maintained, you can find the fork here: https://crates.io/crates/app_dirs2

I'm working on incorporating this and other fixes now.

**Comment by kornelski** [comment]
@icefoxen I recommend that you add other owners to your fork on crates.io, so that your crate won't also have bus factor 1.

**Comment by qezz** [comment]
For those who experiencing this problem in other crates, `.as_ref().into()` compilation error [is not going to be fixed](https://github.com/rust-lang/rust/issues/48716#issuecomment-372419359), so this is a breaking change in compiler

**Comment by icefoxen** [comment]
@kornelski that's the intention. Any volunteers?

**Comment by kornelski** [comment]
I volunteer.

**Comment by icefoxen** [comment]
@kornelski You should have access to the repo and crates.io project; if you don't, let me know.

**Comment by qezz** [comment]
@icefoxen thank you for fork, but there are some inconveniences:

1. It is hard to find the fork via github (because it doesn't include fork into the search result)
2. Is it possible to create an issue within the fork repo? Idk for sure... Anyway, it is hard for people (at least for me) to find the proper repo from here

So, maybe you should create a separate repo (not a fork one)? But I'm still not sure about legal rights / licensing / copyrights...

**Comment by icefoxen** [comment]
@qezz I can add an issue tracker to the fork, but 1) is still a valid point.  I've made an entirely separate repo here: https://github.com/app-dirs-rs/app_dirs2 and updated crates.io to point to it.  Hopefully that will make life simpler.

**Comment by skade** [comment]
Hi, this will break on stable tomorrow, with the release of Rust 1.25. @AndyBarron, can you do a release or at least give someone release rights? I'd also be happy to do that, in this case, add @skade to this repository and skade (florian.gilcher@asquera.de) at crates.io.

**Comment by icefoxen** [comment]
Welcome back to the land of the living, @AndyBarron! https://github.com/app-dirs-rs/app_dirs2/issues/1 has some thoughts on the topic of co-maintenance if you're interested.

**Pull request merged**
